### ISSUE TITLE
run.py, bootComps.py中get_cmdline()の非アトミック処理

### ISSUE THREAD

**Issue by h-sendai** [h-sendai/DAQ-Middleware#10]
run.py, bootComps.py (リモートブートでxinetdから起動する)中にある``get_cmdline()``で順次``/proc/<pid>/cmdline``をopen(), read()している。open()後read()する段階ですでにプロセスが消えread()がエラー番号ESRCHを返すことがある。
DAQコンポーネントを探すためにDAQコンポーネントに無関係のプロセスの``/proc/<pid>/cmdline``も読む必要がある。
open()後read()する段階で当該プロセスが消えread()がエラー番号ESRCHを返すことがある。

open()はtry - exceptで囲んでいるがread()のほうは囲ってなかったのでESRCH exceptionで終了する可能性がある。

修正案
```
def get_cmdline(self, pid):
# 
# 前略
# 
try:
    rv =  [ x for x in f.read().split('\x00') if x ]
except IOError, (en, msg):
    if en == errno.ESRCH:
        return []
    else:
        sys.exit(e)
f.close()
return rv 
```

**Comment by h-sendai** [comment]
ESRCHが返ることの検証コード
```
#!/usr/bin/env python2

import os
import sys
import time
import errno

# sample program to read /proc/<pid>/cmdline
# if the process terminate between open() and read()
# the read() all raise the exception (errno 3, no such process)

# usage:
# % sleep 10 &
# shell print the pid of sleep command
# ./sample <pid_of_sleep>
# raw_input() prompt.  Wait until sleep exit
# then type RETURN

def get_cmdline(pid):
    filename = '/proc/%s/cmdline' % (pid)
    try:
        f = open(filename, 'r')
    except IOError, (en, msg):
        if en == errno.ENOENT:
            return []
        else:
            sys.exit(e)
    raw_input('waiting ...')
    # if the process terminate between open() and read()
    # read() raise exception with ESRCH (errno: 3 no such process).
    try:
        rv =  [ x for x in f.read().split('\x00') if x ]
    except IOError, (en, msg):
        if en == errno.ESRCH:
            return []
        else:
            sys.exit(e)

    f.close()

    return rv

def main():
    if len(sys.argv) != 2:
        sys.stderr.write('Usage: sample.py pid\n')
        sys.exit(1)

    pid = sys.argv[1]

    r = get_cmdline(pid)
    print(r)

if __name__ == '__main__':
    main()
```

sleep 10 &
するとpidが表示される。そのpidを引数にして上のpythonスクリプトを起動する。
``/proc/<pid>/cmdline``をopen()したのち、raw_input()で停止する。10秒待ち、sleep 10が終了したあたりでエンターキーをたたくとESRCHエラーが返るのでmain()側では[]が返る。

**Comment by h-sendai** [comment]
#11 でオーバーラップしている部分(else:)がある。

**Comment by h-sendai** [comment]
修正案メモ

```
diff --git a/bin/run.py b/bin/run.py
index 9a8ba66..fd0cb35 100755
--- a/bin/run.py
+++ b/bin/run.py
@@ -67,8 +67,15 @@ class MyProcUtil:
             if en == errno.ENOENT:
                 return []
             else:
-                sys.exit(e)
-        rv =  [ x for x in f.read().split('\x00') if x ]
+                raise IOError('pid %s: %s' % (pid, msg))
+        try:
+            rv =  [ x for x in f.read().split('\x00') if x ]
+        except IOError, (en, msg):
+            if en == errno.ESRCH:
+                # the process has gone between open() and read().  No problem.
+                return []
+            else:
+                raise IOError('pid %s: %s' % (pid, msg))
         f.close()

         return rv
diff --git a/etc/remote-boot/bootComps.py b/etc/remote-boot/bootComps.py
index 73114c5..73e6b93 100755
--- a/etc/remote-boot/bootComps.py
+++ b/etc/remote-boot/bootComps.py
@@ -41,8 +41,15 @@ class MyProcUtil:
             if en == errno.ENOENT:
                 return []
             else:
-                sys.exit(e)
-        rv =  [ x for x in f.read().split('\x00') if x ]
+                raise IOError('pid %s: %s' % (pid, msg))
+        try:
+            rv =  [ x for x in f.read().split('\x00') if x ]
+        except IOError, (en, msg):
+            if en == errno.ESRCH:
+                return []
+            else:
+                raise IOError('pid %s: %s' % (pid, msg))
+
         f.close()

         return rv
```

**Comment by h-sendai** [comment]
エラーになったときに何が出しているのかわかるようにするために
```
raise IOError('pid %s: %s' % (pid, msg))
```
のメッセージの部分にはプログラム名を入れておく。

**Comment by h-sendai** [comment]
open('/proc/<pid>/cmdline', 'r')でENOENT (no such file or directory)の他にESRCH (no such process)エラーが返ることがある。
commit 0d606d1bd114ac55f2f35540c49644b2270d416d のrun.pyを使って繰り返し起動実験したときのログ:
```
Remote Comps booting... done
DAQ-Opearot Log: /tmp/daqmw/log.Opearator
Now booting the DAQ-Operator...
Traceback (most recent call last):
  File "/usr/bin/run.py", line 977, in <module>
    main()
  File "/usr/bin/run.py", line 969, in main
    ret = DaqOperatorBooting()
  File "/usr/bin/run.py", line 892, in DaqOperatorBooting
    kill_proc_exact(os.path.basename(operator))
  File "/usr/bin/run.py", line 401, in kill_proc_exact
    pids = get_pids_exact(proc_name)
  File "/usr/bin/run.py", line 101, in get_pids_exact
    pid_list = p.get_pids_by_proc_name(proc_name)
  File "/usr/bin/run.py", line 86, in get_pids_by_proc_name
    cmdline = self.get_cmdline(pid)
  File "/usr/bin/run.py", line 70, in get_cmdline
    raise IOError('pid %s: %s' % (pid, msg))
IOError: pid 16833: No such process
```

/proc/<pid>/cmdlineのget_cmdline()中のopen()とread()のエラーは捕捉せず return [] で返すのがよいかも。

**Comment by h-sendai** [comment]
procfsを読む例題
https://man7.org/tlpi/code/online/dist/sysinfo/procfs_user_exe.c.html

**Comment by h-sendai** [comment]
open('/proc/<PID>/cmdline', 'r') でENOENT (no such file or directory)の他にESRCH (no such process)が返るのを実験で確認した。

- processをどんどん作る（たんにusleep()するプログラムを書いてshell scriptで10個バッググラウンドで起動、waitして終了したらまた10個起動する）
- run.pyからopen()などしているところを抜き出して、ENOENTエラー以外だったらraiseする

というので確認した。

**Comment by h-sendai** [comment]
commit 0d606d1bd114ac55f2f35540c49644b2270d416d
commit 373651946095b5cc6f226179d91b9bfc52e5e0e7
で修正した。
